### ISSUE TITLE
Enter space issue in title

### ISSUE THREAD

**Issue by pengx17** [toeverything/blocksuite#1691]

**Comment by Flrande** [comment]
fixed in #1692

**Comment by pengx17** [comment]
This issue still happens in latest build.
Try this:
- enter space multiple times in the middle of the text
- enter space at the end of the title
- delete all texts in the title, enter space (this is critical that the title element will be missing).

**Comment by Flrande** [comment]
fixed in https://github.com/toeverything/blocksuite/pull/2083
