### ISSUE TITLE
When copying content that contains a list, pasting the list results in a break and an empty line.

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#2183]
https://user-images.githubusercontent.com/5910926/233290684-ab92b30a-8fab-4b81-8ebc-f50c8f5a71d1.mp4

**Comment by tzhangchi** [comment]
Unexpected error in codeblock 

https://user-images.githubusercontent.com/5910926/234153818-29e7f967-ddab-4577-a4c0-940af8975822.mp4

**Comment by tzhangchi** [comment]
Pasting the following text into an Apple memo works better than affineClient


https://user-images.githubusercontent.com/5910926/234154004-8e5acf60-5995-470f-85fb-edc06d59a428.mp4

**Comment by doodlewind** [comment]
Sub issue 1: pasted content has redundant blank line
Sub issue 2: deleting content at line start causes content lost

**Comment by zuoxiaodong0815** [comment]
Because the #2438 and #2461 have been fixed, so this issue can be closed.

**Comment by ShortCipher5** [comment]
This issue seems to still exist (v0.5.x-staging-36871e1d9667667718c6bee7891d507142cc5f19):

![Image](https://github.com/toeverything/blocksuite/assets/4605025/9d6ad5c3-1ad6-4c47-aa46-d140fea818bd)

**Comment by ShortCipher5** [comment]
BlockSuite Playground:
![CP](https://github.com/toeverything/blocksuite/assets/4605025/999eb0cc-b8de-4f1c-8090-9ed2b10b918b)
4-445e-ac9b-f03c25a341cf)

**Comment by doodlewind** [comment]
Fixed in latest internal version
